/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "B2DXFitters/Dilution.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

Dilution::Dilution(const char *name, const char *title, 
	RooAbsReal& _omega) :
    RooAbsReal(name,title), 
    omega("omega","omega",this,_omega)
{ 
} 


Dilution::Dilution(const Dilution& other, const char* name) :  
    RooAbsReal(other,name), 
    omega("omega",this,other.omega)
{ 
} 

Dilution::~Dilution() { }


Double_t Dilution::evaluate() const 
{ 
    return 1. - 2. * double(omega);
} 



