/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"

#include "B2DXFitters/IfThreeWayCatPdf.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"

IfThreeWayCatPdf::IfThreeWayCatPdf(const char *name, const char *title,
	RooAbsCategory& _cond, RooAbsReal& _pos, RooAbsReal& _zero,
	RooAbsReal& _neg) : RooAbsPdf(name,title),
    cond("cond","cond",this,_cond), pos("pos","pos",this,_pos),
    zero("zero","zero",this,_zero), neg("neg","neg",this,_neg)
{ }


IfThreeWayCatPdf::IfThreeWayCatPdf(const IfThreeWayCatPdf& other, const char* name) :
    RooAbsPdf(other,name), cond("cond",this,other.cond),
    pos("pos",this,other.pos), zero("zero",this,other.zero),
    neg("neg",this,other.neg)
{ }

IfThreeWayCatPdf::~IfThreeWayCatPdf() { }

Double_t IfThreeWayCatPdf::evaluate() const
{
    // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE
    const int c = cond;
    if (c > 0) return double(pos);
    else if (c < 0) return double(neg);
    else return double(zero);
}
