/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"

#include "B2DXFitters/IfThreeWayPdf.h"
#include "RooAbsReal.h"
#include <cmath>
#include <limits>

IfThreeWayPdf::IfThreeWayPdf(const char *name, const char *title,
	RooAbsReal& _cond, RooAbsReal& _pos, RooAbsReal& _zero,
	RooAbsReal& _neg) : RooAbsPdf(name,title),
    cond("cond","cond",this,_cond), pos("pos","pos",this,_pos),
    zero("zero","zero",this,_zero), neg("neg","neg",this,_neg)
{ }


IfThreeWayPdf::IfThreeWayPdf(const IfThreeWayPdf& other, const char* name) :
    RooAbsPdf(other,name), cond("cond",this,other.cond),
    pos("pos",this,other.pos), zero("zero",this,other.zero),
    neg("neg",this,other.neg)
{ }

IfThreeWayPdf::~IfThreeWayPdf() { }

Double_t IfThreeWayPdf::evaluate() const
{
    // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE
    const double c = cond;
    if (c > double(std::numeric_limits<float>::epsilon()))
	return double(pos);
    else if (c < -double(std::numeric_limits<float>::epsilon()))
	return double(neg);
    else return double(zero);
}
