/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "B2DXFitters/IfThreeWayCat.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

IfThreeWayCat::IfThreeWayCat(const char *name, const char *title, 
	RooAbsCategory& _cond,
	RooAbsReal& _pos,
	RooAbsReal& _zero,
	RooAbsReal& _neg) :
    RooAbsReal(name,title), 
    cond("cond","cond",this,_cond),
    pos("pos","pos",this,_pos),
    zero("zero","zero",this,_zero),
    neg("neg","neg",this,_neg)
{ 
} 


IfThreeWayCat::IfThreeWayCat(const IfThreeWayCat& other, const char* name) :  
    RooAbsReal(other,name), 
    cond("cond",this,other.cond),
    pos("pos",this,other.pos),
    zero("zero",this,other.zero),
    neg("neg",this,other.neg)
{ 
} 

IfThreeWayCat::~IfThreeWayCat() { }


Double_t IfThreeWayCat::evaluate() const 
{ 
    const int c = (int) cond;
    if (c > 0) return double(pos); 
    else if (c < 0) return double(neg);
    else return double(zero);
} 



