/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "B2DXFitters/IfThreeWay.h" 
#include "RooAbsReal.h" 
#include <cmath>
#include <limits>

IfThreeWay::IfThreeWay(const char *name, const char *title, 
	RooAbsReal& _cond,
	RooAbsReal& _pos,
	RooAbsReal& _zero,
	RooAbsReal& _neg) :
    RooAbsReal(name,title), 
    cond("cond","cond",this,_cond),
    pos("pos","pos",this,_pos),
    zero("zero","zero",this,_zero),
    neg("neg","neg",this,_neg)
{ 
} 


IfThreeWay::IfThreeWay(const IfThreeWay& other, const char* name) :  
    RooAbsReal(other,name), 
    cond("cond",this,other.cond),
    pos("pos",this,other.pos),
    zero("zero",this,other.zero),
    neg("neg",this,other.neg)
{ 
} 

IfThreeWay::~IfThreeWay() { }


Double_t IfThreeWay::evaluate() const 
{ 
    const double c = (double) cond;
    //cout << "ID is " << c <<endl;
    if (c > double(std::numeric_limits<float>::epsilon())) {
        //cout << "Returning pos " << pos << endl;
	    return double(pos); 
    } else {
        if (c < -double(std::numeric_limits<float>::epsilon())){
            //cout << "Returning neg " << neg << endl;
	        return double(neg);
        } else {
            //cout << "Returning zero " << zero << endl;
            return double(zero);
        }
    }
} 



