/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "B2DXFitters/Inverse.h" 

Inverse::Inverse(const char *name, const char *title, 
	RooAbsReal& _val) :
    RooAbsReal(name,title), 
    val("val","val",this,_val)
{ 
} 


Inverse::Inverse(const Inverse& other, const char* name) :  
    RooAbsReal(other,name), 
    val("val",this,other.val)
{ 
} 

Inverse::~Inverse() { }


Double_t Inverse::evaluate() const 
{
    return 1. / double(val);
}
