/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "B2DXFitters/SquaredSum.h" 

SquaredSum::SquaredSum(const char *name, const char *title, 
	RooAbsReal& _C, RooAbsReal& _D, RooAbsReal& _S) :
    RooAbsReal(name,title), 
    C("C","C",this,_C), D("D","D",this,_D), S("S","S",this,_S)
{ 
} 


SquaredSum::SquaredSum(const SquaredSum& other, const char* name) :  
    RooAbsReal(other,name), 
    C("C",this,other.C), D("D",this,other.D), S("S",this,other.S)
{ 
} 

SquaredSum::~SquaredSum() { }


Double_t SquaredSum::evaluate() const 
{ 
    double c = C, d = D, s = S;
    return c * c + d * d + s * s;
} 



