/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "B2DXFitters/TagDLLToTagEta.h" 
#include "RooAbsReal.h" 

#include "B2DXFitters/TagCombiner.h"

TagDLLToTagEta::TagDLLToTagEta(const char *name, const char *title, 
	RooAbsReal& _dll) :
    RooAbsReal(name,title), 
    dll("dll","dll",this,_dll)
{ 
} 


TagDLLToTagEta::TagDLLToTagEta(const TagDLLToTagEta& other, const char* name) :  
    RooAbsReal(other,name), 
    dll("dll",this,other.dll)
{ 
} 

TagDLLToTagEta::~TagDLLToTagEta() { }


Double_t TagDLLToTagEta::evaluate() const 
{
    return TagTools::tagEta(double(dll));
}
