/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "B2DXFitters/TagEfficiencyWeight.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include <cmath>
#include <limits>

TagEfficiencyWeight::TagEfficiencyWeight(const char *name, const char *title, 
	RooAbsCategory& _tag,
	RooAbsReal& _eff) :
    RooAbsReal(name,title), 
    tag("tag","tag",this,_tag),
    eff("eff","eff",this,_eff)
{ 
} 

TagEfficiencyWeight::TagEfficiencyWeight(const TagEfficiencyWeight& other, const char* name) :  
    RooAbsReal(other,name), 
    tag("tag",this,other.tag),
    eff("eff",this,other.eff)
{ 
} 

TagEfficiencyWeight::~TagEfficiencyWeight() { }


Double_t TagEfficiencyWeight::evaluate() const 
{
    int t = tag;
    if (t) return double(eff);
    else return 1. - double(eff);
}
