/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef COMBBKGPTPDF
#define COMBBKGPTPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"


class CombBkgPTPdf : public RooAbsPdf {
public:
  CombBkgPTPdf() {}; 
  CombBkgPTPdf(const char *name, const char *title,
	      RooAbsReal& _t,
	      RooAbsReal& _a,
	      RooAbsReal& _f,
	      RooAbsReal& _alpha,
	      RooAbsReal& _beta);
  CombBkgPTPdf(const CombBkgPTPdf& other, const char* name=0);
  virtual TObject* clone(const char* newname) const { return new CombBkgPTPdf(*this,newname); }
  inline virtual ~CombBkgPTPdf() { }

  virtual Int_t getAnalyticalIntegral(
	  RooArgSet& allVars, RooArgSet& integVars, const char* range) const;
  virtual Double_t analyticalIntegral(Int_t code, const char* range) const;

protected:

  RooRealProxy t;
  RooRealProxy a;
  RooRealProxy f;
  RooRealProxy alpha;
  RooRealProxy beta;
  
  Double_t evaluate() const;

private:
  double monoInt(double t, double a, double alpha) const;

  ClassDef(CombBkgPTPdf,1) // Your description goes here...
};
 
#endif
