/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef DILUTION
#define DILUTION

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class Dilution : public RooAbsReal {
public:
  Dilution() {} ; 
  Dilution(const char *name, const char *title,
	      RooAbsReal& _omega);
  Dilution(const Dilution& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Dilution(*this,newname); }
  virtual ~Dilution();

protected:

  RooRealProxy omega;
  
  Double_t evaluate() const;

private:
  ClassDef(Dilution, 1);
};
 
#endif
