/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef DTACCEPTANCELHCBNOTE2007041
#define DTACCEPTANCELHCBNOTE2007041

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class DTAcceptanceLHCbNote2007041 : public RooAbsReal {
public:
  DTAcceptanceLHCbNote2007041() {} ; 
  DTAcceptanceLHCbNote2007041(const char *name, const char *title,
	      RooAbsReal& _t,
	      RooAbsReal& _s_low,
	      RooAbsReal& _s_high,
	      RooAbsReal& _n,
	      RooAbsReal& _limit);
  DTAcceptanceLHCbNote2007041(const DTAcceptanceLHCbNote2007041& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new DTAcceptanceLHCbNote2007041(*this,newname); }
  inline virtual ~DTAcceptanceLHCbNote2007041() { }

protected:

  RooRealProxy t ;
  RooRealProxy s_low ;
  RooRealProxy s_high ;
  RooRealProxy n ;
  RooRealProxy limit ;
  
  Double_t evaluate() const ;

private:

  ClassDef(DTAcceptanceLHCbNote2007041,1) // Your description goes here...
};
 
#endif
