/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef IFTHREEWAY
#define IFTHREEWAY

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooAbsReal.h"
 
class IfThreeWay : public RooAbsReal {
public:
  IfThreeWay() {} ; 
  IfThreeWay(const char *name, const char *title,
	      RooAbsReal& _cond,
	      RooAbsReal& _pos,
	      RooAbsReal& _zero,
	      RooAbsReal& _neg);
  IfThreeWay(const IfThreeWay& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new IfThreeWay(*this,newname); }
  virtual ~IfThreeWay();

protected:

  RooRealProxy cond;
  RooRealProxy pos;
  RooRealProxy zero;
  RooRealProxy neg;
  
  Double_t evaluate() const;

private:
  ClassDef(IfThreeWay, 1);
};
 
#endif
