/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef IFTHREEWAYCATPDF
#define IFTHREEWAYCATPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class IfThreeWayCatPdf : public RooAbsPdf {
    public:
	IfThreeWayCatPdf() {} ; 
	IfThreeWayCatPdf(const char *name, const char *title,
		RooAbsCategory& _cond,
		RooAbsReal& _pos,
		RooAbsReal& _zero,
		RooAbsReal& _neg);
	IfThreeWayCatPdf(const IfThreeWayCatPdf& other, const char* name=0) ;
	virtual TObject* clone(const char* newname) const { return new IfThreeWayCatPdf(*this,newname); }
	virtual ~IfThreeWayCatPdf();

    protected:

	RooCategoryProxy cond;
	RooRealProxy pos;
	RooRealProxy zero;
	RooRealProxy neg;

	Double_t evaluate() const ;

    private:

	ClassDef(IfThreeWayCatPdf,1) // Your description goes here...
};

#endif
