/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef IFTHREEWAYPDF
#define IFTHREEWAYPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooAbsReal.h"
 
class IfThreeWayPdf : public RooAbsPdf {
    public:
	IfThreeWayPdf() {} ; 
	IfThreeWayPdf(const char *name, const char *title,
		RooAbsReal& _cond,
		RooAbsReal& _pos,
		RooAbsReal& _zero,
		RooAbsReal& _neg);
	IfThreeWayPdf(const IfThreeWayPdf& other, const char* name=0) ;
	virtual TObject* clone(const char* newname) const { return new IfThreeWayPdf(*this,newname); }
	virtual ~IfThreeWayPdf();

    protected:

	RooRealProxy cond;
	RooRealProxy pos;
	RooRealProxy zero;
	RooRealProxy neg;

	Double_t evaluate() const ;

    private:

	ClassDef(IfThreeWayPdf,1) // Your description goes here...
};

#endif
