/** @file   PowLawAcceptance.h
 * @author Suvayu Ali <Suvayu.Ali@cern.ch>
 * @date   Thu May 17 21:47:46 2012
 *
 * @brief  This class implements a power law acceptance function.
 *
 *         This code is based on a skeleton code generated by
 *         RooClassFactory from RooFit. The functional form and the
 *         integral was coded in by hand.
 *
 */


#ifndef __POWLAWACCEPTANCE_H
#define __POWLAWACCEPTANCE_H

#include <RooAbsReal.h>
#include <RooRealProxy.h>
#include <RooCategoryProxy.h>
#include <RooAbsCategory.h>
#include <RooConstVar.h>

class PowLawAcceptance : public RooAbsReal {
public:

  PowLawAcceptance();
  PowLawAcceptance(const char *name, const char *title,
		   RooAbsReal& turnon, RooAbsReal& time,
		   RooAbsReal& offset, RooAbsReal& exponent,
		   RooAbsReal& beta, RooAbsReal* correction=0);
  PowLawAcceptance(const PowLawAcceptance& other, const char* name=0);
  PowLawAcceptance(const PowLawAcceptance& other, const char* name,
		   RooAbsReal* correction);
  virtual ~PowLawAcceptance();
  virtual TObject* clone(const char* newname) const;
  PowLawAcceptance& operator=(const PowLawAcceptance& other);

protected:

  Double_t evaluate() const;

  RooRealProxy _turnon;
  RooRealProxy _time;
  RooRealProxy _offset;
  RooRealProxy _exponent;
  RooRealProxy _beta;
  static RooConstVar  _one;
  RooRealProxy _correction;

private:

  ClassDef(PowLawAcceptance,2);	// Implements a power law acceptance function.
};

#endif	// __POWLAWACCEPTANCE_H
