/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef SQUAREDSUM
#define SQUAREDSUM

#include "RooAbsReal.h"
#include "RooRealProxy.h"
 
class SquaredSum : public RooAbsReal {
public:
  SquaredSum() {} ; 
  SquaredSum(const char *name, const char *title,
	      RooAbsReal& _C, RooAbsReal& _D, RooAbsReal& _S);
  SquaredSum(const SquaredSum& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new SquaredSum(*this,newname); }
  virtual ~SquaredSum();

protected:

  RooRealProxy C;
  RooRealProxy D;
  RooRealProxy S;
  
  Double_t evaluate() const;

private:
  ClassDef(SquaredSum, 1);
};
 
#endif
