/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef TAGEFFICIENCYWEIGHT
#define TAGEFFICIENCYWEIGHT

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class TagEfficiencyWeight : public RooAbsReal {
public:
  TagEfficiencyWeight() {} ; 
  TagEfficiencyWeight(const char *name, const char *title,
	      RooAbsCategory& _tag,
	      RooAbsReal& _eff);
  TagEfficiencyWeight(const TagEfficiencyWeight& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new TagEfficiencyWeight(*this,newname); }
  virtual ~TagEfficiencyWeight();

protected:

  RooCategoryProxy tag;
  RooRealProxy eff;
  
  Double_t evaluate() const;

private:
  ClassDef(TagEfficiencyWeight, 1);
};
 
#endif
